# Generated by Django 3.0.5 on 2022-01-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEWS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
